#!/bin/bash
project=trunk
cwd=`pwd`

# Print info about the machine.
cat /proc/cpuinfo > cpu.info
cat /proc/meminfo > mem.info

function hw() {
    # Clone the project.
    svn checkout -r 1569015 http://svn.apache.org/repos/asf/commons/proper/lang/trunk/
    # Go to a specific revision.
    ( cd ${project}; )
     # Run the tests.
    ( cd ${project}; mvn test )
}
# Step 1 of the homework.
hw | tee step1.txt
sed -i 's/.*'"${cwd//\//\\/}"'/USER/g' step1.txt
